import '../models/user_model.dart';
import '../models/match_model.dart';
import '../models/message_model.dart';

const kCurrentUserId = 'current_user';

class MockData {
  static final UserModel currentUser = UserModel(
    id: kCurrentUserId,
    email: 'alex@university.edu',
    name: 'Alex Johnson',
    age: 21,
    major: 'Business Administration',
    university: 'State University',
    bio: 'Junior looking for a chill roommate. I keep my space clean and respect quiet hours during the week.',
    photoUrls: ['https://i.pravatar.cc/400?img=12'],
    questionnaire: const Questionnaire(
      sleepSchedule: 'flexible',
      cleanliness: 4,
      fridayNight: 'lowkey',
      guestsFrequency: 'monthly',
      overnightGuests: 'heads_up',
      noiseLevel: 'background',
      morningRoutine: 'moderate',
      kitchenHabits: 'reheat',
      sharingComfort: 'some',
      rentBudget: '600_900',
      homeFrequency: 'sometimes',
      smoking: false,
      drinking: false,
      pets: false,
    ),
    isProfileComplete: true,
    createdAt: DateTime(2025, 8, 15),
  );

  static final List<UserModel> profiles = [
    UserModel(
      id: 'user_1',
      email: 'emma@stanford.edu',
      name: 'Emma Chen',
      age: 20,
      major: 'Computer Science',
      university: 'Stanford University',
      bio: 'CS junior who loves hiking and late-night coding sessions. Looking for a tidy roommate who respects quiet hours.',
      photoUrls: ['https://i.pravatar.cc/400?img=47'],
      questionnaire: const Questionnaire(
        sleepSchedule: 'early_bird',
        cleanliness: 5,
        fridayNight: 'studying',
        guestsFrequency: 'rarely',
        overnightGuests: 'heads_up',
        noiseLevel: 'quiet',
        morningRoutine: 'moderate',
        kitchenHabits: 'cook',
        sharingComfort: 'some',
        rentBudget: '900_1200',
        homeFrequency: 'often',
        smoking: false,
        drinking: false,
        pets: true,
      ),
      isProfileComplete: true,
      createdAt: DateTime(2025, 9, 1),
    ),
    UserModel(
      id: 'user_2',
      email: 'marcus@ucla.edu',
      name: 'Marcus Williams',
      age: 22,
      major: 'Pre-Medicine',
      university: 'UCLA',
      bio: 'Med-track senior. I study a lot but always up for a good conversation. Very respectful of shared spaces.',
      photoUrls: ['https://i.pravatar.cc/400?img=3'],
      questionnaire: const Questionnaire(
        sleepSchedule: 'flexible',
        cleanliness: 4,
        fridayNight: 'lowkey',
        guestsFrequency: 'monthly',
        overnightGuests: 'heads_up',
        noiseLevel: 'background',
        morningRoutine: 'quick',
        kitchenHabits: 'cook',
        sharingComfort: 'some',
        rentBudget: '600_900',
        homeFrequency: 'sometimes',
        smoking: false,
        drinking: false,
        pets: false,
      ),
      isProfileComplete: true,
      createdAt: DateTime(2025, 9, 5),
    ),
    UserModel(
      id: 'user_3',
      email: 'sofia@nyu.edu',
      name: 'Sofia Rodriguez',
      age: 21,
      major: 'Psychology',
      university: 'NYU',
      bio: 'Psychology junior, plant mom, and amateur chef. I love keeping common areas clean and hosting occasional dinners.',
      photoUrls: ['https://i.pravatar.cc/400?img=48'],
      questionnaire: const Questionnaire(
        sleepSchedule: 'night_owl',
        cleanliness: 4,
        fridayNight: 'party',
        guestsFrequency: 'weekends',
        overnightGuests: 'fine',
        noiseLevel: 'lively',
        morningRoutine: 'long',
        kitchenHabits: 'cook',
        sharingComfort: 'share',
        rentBudget: '900_1200',
        homeFrequency: 'sometimes',
        smoking: false,
        drinking: true,
        pets: true,
      ),
      isProfileComplete: true,
      createdAt: DateTime(2025, 9, 10),
    ),
    UserModel(
      id: 'user_4',
      email: 'jake@gatech.edu',
      name: 'Jake Thompson',
      age: 19,
      major: 'Mechanical Engineering',
      university: 'Georgia Tech',
      bio: 'Freshman engineer. Clean, organized, and usually up by 7am. Big college football fan on weekends.',
      photoUrls: ['https://i.pravatar.cc/400?img=15'],
      questionnaire: const Questionnaire(
        sleepSchedule: 'early_bird',
        cleanliness: 4,
        fridayNight: 'lowkey',
        guestsFrequency: 'monthly',
        overnightGuests: 'heads_up',
        noiseLevel: 'background',
        morningRoutine: 'quick',
        kitchenHabits: 'reheat',
        sharingComfort: 'some',
        rentBudget: '600_900',
        homeFrequency: 'rarely',
        smoking: false,
        drinking: false,
        pets: false,
      ),
      isProfileComplete: true,
      createdAt: DateTime(2025, 9, 12),
    ),
    UserModel(
      id: 'user_5',
      email: 'priya@wharton.edu',
      name: 'Priya Patel',
      age: 20,
      major: 'Finance',
      university: 'Wharton School',
      bio: 'Finance sophomore balancing coursework and entrepreneurship club. Super tidy, early riser, and love morning yoga.',
      photoUrls: ['https://i.pravatar.cc/400?img=49'],
      questionnaire: const Questionnaire(
        sleepSchedule: 'early_bird',
        cleanliness: 5,
        fridayNight: 'studying',
        guestsFrequency: 'rarely',
        overnightGuests: 'prefer_not',
        noiseLevel: 'quiet',
        morningRoutine: 'long',
        kitchenHabits: 'cook',
        sharingComfort: 'separate',
        rentBudget: '1200_plus',
        homeFrequency: 'often',
        smoking: false,
        drinking: false,
        pets: false,
      ),
      isProfileComplete: true,
      createdAt: DateTime(2025, 9, 14),
    ),
    UserModel(
      id: 'user_6',
      email: 'tyler@northwestern.edu',
      name: 'Tyler Brooks',
      age: 21,
      major: 'Journalism',
      university: 'Northwestern University',
      bio: 'Journalism junior and part-time barista. I write late into the night but I use headphones. Friendly and social on weekends.',
      photoUrls: ['https://i.pravatar.cc/400?img=27'],
      questionnaire: const Questionnaire(
        sleepSchedule: 'night_owl',
        cleanliness: 3,
        fridayNight: 'party',
        guestsFrequency: 'always',
        overnightGuests: 'fine',
        noiseLevel: 'lively',
        morningRoutine: 'quick',
        kitchenHabits: 'eat_out',
        sharingComfort: 'share',
        rentBudget: '600_900',
        homeFrequency: 'rarely',
        smoking: false,
        drinking: true,
        pets: false,
      ),
      isProfileComplete: true,
      createdAt: DateTime(2025, 9, 16),
    ),
    UserModel(
      id: 'user_7',
      email: 'aisha@howard.edu',
      name: 'Aisha Johnson',
      age: 22,
      major: 'Biology',
      university: 'Howard University',
      bio: 'Biology senior focused on research. Clean and quiet during the week, love cooking on weekends.',
      photoUrls: ['https://i.pravatar.cc/400?img=44'],
      questionnaire: const Questionnaire(
        sleepSchedule: 'early_bird',
        cleanliness: 5,
        fridayNight: 'studying',
        guestsFrequency: 'rarely',
        overnightGuests: 'heads_up',
        noiseLevel: 'quiet',
        morningRoutine: 'moderate',
        kitchenHabits: 'cook',
        sharingComfort: 'some',
        rentBudget: '600_900',
        homeFrequency: 'often',
        smoking: false,
        drinking: false,
        pets: false,
      ),
      isProfileComplete: true,
      createdAt: DateTime(2025, 9, 18),
    ),
    UserModel(
      id: 'user_8',
      email: 'liam@cornell.edu',
      name: 'Liam O\'Brien',
      age: 20,
      major: 'Architecture',
      university: 'Cornell University',
      bio: 'Architecture sophomore. My desk might be chaotic but the common areas stay clean. Love a good roommate who\'s down to explore the city.',
      photoUrls: ['https://i.pravatar.cc/400?img=68'],
      questionnaire: const Questionnaire(
        sleepSchedule: 'flexible',
        cleanliness: 3,
        fridayNight: 'lowkey',
        guestsFrequency: 'monthly',
        overnightGuests: 'fine',
        noiseLevel: 'background',
        morningRoutine: 'moderate',
        kitchenHabits: 'eat_out',
        sharingComfort: 'share',
        rentBudget: '900_1200',
        homeFrequency: 'sometimes',
        smoking: false,
        drinking: true,
        pets: true,
      ),
      isProfileComplete: true,
      createdAt: DateTime(2025, 9, 20),
    ),
  ];

  // Pre-built matches: current user is matched with Emma and Marcus
  static List<MatchModel> matchesFor(String userId) {
    return [
      MatchModel(
        id: 'match_1',
        userIds: [userId, 'user_1'],
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        lastMessage: 'Yeah I think we\'d be a great match!',
        lastMessageAt: DateTime.now().subtract(const Duration(hours: 3)),
        readStatus: {userId: true, 'user_1': false},
      ),
      MatchModel(
        id: 'match_2',
        userIds: [userId, 'user_2'],
        createdAt: DateTime.now().subtract(const Duration(hours: 5)),
        readStatus: {userId: true, 'user_2': false},
      ),
    ];
  }

  // Pre-built messages for match_1
  static List<MessageModel> messagesFor(String matchId, String currentUserId) {
    if (matchId != 'match_1') return [];
    return [
      MessageModel(
        id: 'msg_1',
        senderId: 'user_1',
        text: 'Hey! I saw we matched. Your profile looks really cool 😊',
        createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 1)),
        isRead: true,
      ),
      MessageModel(
        id: 'msg_2',
        senderId: currentUserId,
        text: 'Thanks! I love your profile too. What\'s your schedule usually like?',
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        isRead: true,
      ),
      MessageModel(
        id: 'msg_3',
        senderId: 'user_1',
        text: 'Pretty chill during weekdays, early to bed. Weekends I might have a few friends over. You cool with that?',
        createdAt: DateTime.now().subtract(const Duration(hours: 5)),
        isRead: true,
      ),
      MessageModel(
        id: 'msg_4',
        senderId: currentUserId,
        text: 'Yeah I think we\'d be a great match!',
        createdAt: DateTime.now().subtract(const Duration(hours: 3)),
        isRead: true,
      ),
    ];
  }

  static UserModel? getUserById(String id) {
    if (id == kCurrentUserId) return currentUser;
    try {
      return profiles.firstWhere((p) => p.id == id);
    } catch (_) {
      return null;
    }
  }
}
